# on: 
#   push:
#     branches:
#       - 'main'
#     paths:
#       - 'website_material/**'
name: Copy Files
on: 
  issues:
    types: 
      - labeled
      
jobs:
  update-doi:
    if: contains(github.event.label.name, 'published')
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.update-doi.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r .github/scripts/requirements.txt

      - name: update doi
        id: update-doi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          SUCCESS=$(python3 .github/scripts/update_doi.py)
          echo "success=${SUCCESS}" >> $GITHUB_OUTPUT

  copy-files:
    needs: update-doi
    if: ${{ needs.update-doi.outputs.success == 'True' }}
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r .github/scripts/requirements.txt

      - name: create token for website repo
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: 'website'

      - name: create branch
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: 'website'
          BRANCH_NAME: ${{ github.event.repository.name }}
        run: |
          python3 .github/scripts/create_branch.py


      - name: copy files to website repo
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          SOURCE_REPO_OWNER: ${{ github.repository_owner }}
          SOURCE_REPO_NAME: ${{ github.event.repository.name }}
          SOURCE_PATH: 'website_material'
          TARGET_REPO_OWNER: ${{ github.repository_owner }}
          TARGET_REPO_NAME: 'website'
          TARGET_REPO_BRANCH: ${{ github.event.repository.name }}
          TARGET_PATH: 'src/pages/models/${{ github.event.repository.name }}'
        run: |
          python3 .github/scripts/copy_files.py

      - name: update submission issue
        env:
          GITHUB_TOKEN:  ${{ steps.app-token.outputs.token }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: 'Model_Submission'
          SLUG: ${{ github.event.repository.name }}
        run: |
          python3 .github/scripts/update_labels.py